### PR TITLE
Create dobermano.json

### PR DESCRIPTION
**Pull request by rjsimp01**

### CODE REVIEW

**Comment by rjsimp01** [comment]
I'm fixing right now, just a moment

**Review by zanicar — COMMENTED** [review]
`signature verification failed; please verify account number (0) and chain-id (quicksilver-1): unauthorized`

**Comment by rjsimp01** [comment]
I'm fixing, wait few minutes please

**Comment by rjsimp01** [comment]
updated, please check

**Review by zanicar — APPROVED** [review]
lgtm

**Pull request merged**
