### PR TITLE
Oni Gentx

### PR DESCRIPTION
**Pull request by onivalidator**

### CODE REVIEW

**Comment by onivalidator** [comment]
Fixed the Gentx with a new blob

**Review by zanicar — CHANGES_REQUESTED** [review]
`failed to execute message; message index: 0: got: secp256k1, expected: [ed25519]: validator pubkey type is not supported`

**Comment by onivalidator** [comment]
Updated with correct Gentx - sorry about the pubkey mismatch.

**Review by zanicar — APPROVED** [review]
lgtm

**Pull request merged**
