### PR TITLE
GENTX Active Nodes

### PR DESCRIPTION
**Pull request by activenodes**

### CODE REVIEW

**Comment by zanicar** [comment]
`signature verification failed; please verify account number (0) and chain-id (quicksilver-1): unauthorized`

**Comment by activenodes** [comment]
> `signature verification failed; please verify account number (0) and chain-id (quicksilver-1): unauthorized`

Give me a moment to check and generate a new one

**Comment by activenodes** [comment]
@zanicar gentx updated

**Review by zanicar — APPROVED** [review]
lgtm

**Pull request merged**
